
title: My Resume
url: 'http://nexlabs.co'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Myo Htet Aung 
tagline: Co-Founder
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email:myohtetaung@icloud.com
phone:959 9755 40 768
linkedin: myohtetaung
twitter: '@myohtetaung87'

#Update all the sections by editing the files inside _includes folder.
